# Generated by Django 5.0.6 on 2024-06-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopapp', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marked_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
    ]
