# Generated by Django 5.0.6 on 2024-06-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopapp', '0003_remove_product_marked_price_remove_product_warranty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='rate',
            new_name='price',
        ),
    ]
