# Generated by Django 5.0.6 on 2024-06-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopapp', '0004_rename_rate_cartproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Receieved', 'Order Received'), ('Order Cancelled', 'Order Cancelled')], max_length=200),
        ),
    ]
